// <auto-generated />
using System;
using BudgetingApp.Models.RepositoryModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetingApp.Migrations
{
    [DbContext(typeof(BudgetingContext))]
    partial class BudgetingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetingApp.Models.BudgetingModels.Budget", b =>
                {
                    b.Property<long>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BudgetId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("BudgetId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("BudgetingApp.Models.BudgetingModels.ExpenseCategory", b =>
                {
                    b.Property<long>("ExpenseCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ExpenseCategoryId"));

                    b.Property<long>("BudgetId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BudgetedAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("ExpenseCategoryId");

                    b.HasIndex("BudgetId");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("BudgetingApp.Models.BudgetingModels.ExpenseItem", b =>
                {
                    b.Property<long>("ExpenseItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ExpenseItemId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<long?>("BudgetId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("ExpenseCategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("ExpenseItemId");

                    b.HasIndex("BudgetId");

                    b.HasIndex("ExpenseCategoryId");

                    b.ToTable("ExpenseItems");
                });

            modelBuilder.Entity("BudgetingApp.Models.BudgetingModels.IncomeCategory", b =>
                {
                    b.Property<long>("IncomeCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IncomeCategoryId"));

                    b.Property<long>("BudgetId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BudgetedAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("IncomeCategoryId");

                    b.HasIndex("BudgetId");

                    b.ToTable("IncomeCategories");
                });

            modelBuilder.Entity("BudgetingApp.Models.BudgetingModels.IncomeItem", b =>
                {
                    b.Property<long>("IncomeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IncomeItemId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<long?>("BudgetId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("IncomeCategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("IncomeItemId");

                    b.HasIndex("BudgetId");

                    b.HasIndex("IncomeCategoryId");

                    b.ToTable("IncomeItems");
                });

            modelBuilder.Entity("BudgetingApp.Models.BudgetingModels.ExpenseCategory", b =>
                {
                    b.HasOne("BudgetingApp.Models.BudgetingModels.Budget", "Budget")
                        .WithMany("ExpenseCategories")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("BudgetingApp.Models.BudgetingModels.ExpenseItem", b =>
                {
                    b.HasOne("BudgetingApp.Models.BudgetingModels.Budget", "Budget")
                        .WithMany("ExpenseItems")
                        .HasForeignKey("BudgetId");

                    b.HasOne("BudgetingApp.Models.BudgetingModels.ExpenseCategory", "ExpenseCategory")
                        .WithMany("ExpenseItems")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("ExpenseCategory");
                });

            modelBuilder.Entity("BudgetingApp.Models.BudgetingModels.IncomeCategory", b =>
                {
                    b.HasOne("BudgetingApp.Models.BudgetingModels.Budget", "Budget")
                        .WithMany("IncomeCategories")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("BudgetingApp.Models.BudgetingModels.IncomeItem", b =>
                {
                    b.HasOne("BudgetingApp.Models.BudgetingModels.Budget", "Budget")
                        .WithMany("IncomeItems")
                        .HasForeignKey("BudgetId");

                    b.HasOne("BudgetingApp.Models.BudgetingModels.IncomeCategory", "IncomeCategory")
                        .WithMany("IncomeItems")
                        .HasForeignKey("IncomeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("IncomeCategory");
                });

            modelBuilder.Entity("BudgetingApp.Models.BudgetingModels.Budget", b =>
                {
                    b.Navigation("ExpenseCategories");

                    b.Navigation("ExpenseItems");

                    b.Navigation("IncomeCategories");

                    b.Navigation("IncomeItems");
                });

            modelBuilder.Entity("BudgetingApp.Models.BudgetingModels.ExpenseCategory", b =>
                {
                    b.Navigation("ExpenseItems");
                });

            modelBuilder.Entity("BudgetingApp.Models.BudgetingModels.IncomeCategory", b =>
                {
                    b.Navigation("IncomeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
